### ISSUE TITLE
error messages empty

### ISSUE THREAD

**Issue by fonta** [DiscordMusicBot/MusicBot#17]
Lots of error messages are empty.
http://i.imgur.com/EP0Wk5H.png

or when someone gives a command while not being in the voicechannel:
http://i.imgur.com/itwoDS1.png

**Comment by TBK** [comment]
My guess is it is related to the API version changes that Discord is making. Think the discord.py lib uses API v3 and soon the only allowed version is v6.

**Comment by fonta** [comment]
Well, I'm wondering if thats the case because only the messages where you use markdown dont work.
The reasons can be found in the console though:
http://i.imgur.com/Nf0jCwu.png - http://i.imgur.com/nJ7E31I.png
while messages without the markdown:
http://i.imgur.com/KfpwujU.png

**Comment by fonta** [comment]
Seems it's easily fixed:
http://i.imgur.com/2Ze2D4f.png
Created a PR: https://github.com/DiscordMusicBot/MusicBot/pull/19

**Comment by TBK** [comment]
Thanks for the PR.

**Comment by fonta** [comment]
@TBK0000 No problem! Thanks for accepting :)
