### ISSUE TITLE
fwd and rwd breaks np

### ISSUE THREAD

**Issue by fonta** [DiscordMusicBot/MusicBot#21]
If you use fwd or rwd, you can't use skip, np, etc anymore because the bot thinks nothing is playing.
http://i.imgur.com/RtUUXX9.png

**Comment by MinoLiu** [comment]
This bug I think the occurred reason should be

#### _play_entry faster than killed ffmpeg_player callback (_playback_finished)

so _current_player and _current_entry were None.

Created a PR: #28 

also fix some other bugs

**Comment by TBK** [comment]
#28 Fixed the issue.
