### ISSUE TITLE
Not connected, while it is.

### ISSUE THREAD

**Issue by fonta** [DiscordMusicBot/MusicBot#22]
I guess it's the new websockets zip you've added to the dockerfile, creates a lot of errors.
The bot does connect to the channel, but keeps retrying.

https://hastebin.com/etiwiniyuj.log

**Comment by fonta** [comment]
While version 3.3 doesn't work, version 3.2 works just fine:
```
&& pip3 install --upgrade --force-reinstall https://github.com/aaugustin/websockets/archive/3.2.zip \
```

**Comment by TBK** [comment]
It is still an issue with websockets version 3.4?

The websockets lib has had a lot of changes/improvements lately.

**Comment by fonta** [comment]
Trying right now.

**Comment by fonta** [comment]
3.4 seems to work!

**Comment by TBK** [comment]
Super :)
