### ISSUE TITLE
InstaSkip doesn't work

### ISSUE THREAD

**Issue by PacificBlackDuck** [DiscordMusicBot/MusicBot#26]
I have set myself as owner, added users to the [DJ] group yet when I try to !skip, it doesn't skip instantly. I'm not getting errors either. Commands like !listids work fine.

**Comment by fonta** [comment]
Maybe read the help? https://i.imgur.com/M4O0FLU.png

**Comment by PacificBlackDuck** [comment]
Oops didn't see that. Thanks.
